# Generated by Django 3.1.6 on 2021-03-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, editable=False, verbose_name='Activo(a)')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modification_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('message', models.TextField(verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'contáctenos',
                'verbose_name_plural': 'contáctenos',
                'ordering': ['name'],
            },
        ),
    ]
